name_zh: 洛天依
name_en: LuoTianyi
nickname: [ "天依", "Luo Tianyi" ]
qq_id: 1121221045

paths:
  music_dirs:
    - F:/Audio/Music

  random_picture_dirs:
    - F:/Picture/pixiv/LuoTianyi

  lyric_dirs:
    - F:/Audio/Music/Lyric/LuoTianyi